add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen01_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen01_1.C [inlineEverything_specimen01_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen01_1.C"									 		NINLINE="$(echo specimen01_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen01_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen02_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen02_1.C [inlineEverything_specimen02_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen02_1.C"									 		NINLINE="$(echo specimen02_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen02_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen03_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen03_1.C [inlineEverything_specimen03_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen03_1.C"									 		NINLINE="$(echo specimen03_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen03_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen04_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen04_1.C [inlineEverything_specimen04_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen04_1.C"									 		NINLINE="$(echo specimen04_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen04_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen05_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen05_1.C [inlineEverything_specimen05_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen05_1.C"									 		NINLINE="$(echo specimen05_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen05_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen06_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen06_1.C [inlineEverything_specimen06_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen06_1.C"									 		NINLINE="$(echo specimen06_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen06_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen07_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen07_1.C [inlineEverything_specimen07_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen07_1.C"									 		NINLINE="$(echo specimen07_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen07_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen08_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen08_1.C [inlineEverything_specimen08_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen08_1.C"									 		NINLINE="$(echo specimen08_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen08_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen09_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen09_1.C [inlineEverything_specimen09_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen09_1.C"									 		NINLINE="$(echo specimen09_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen09_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen10_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen10_1.C [inlineEverything_specimen10_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen10_1.C"									 		NINLINE="$(echo specimen10_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen10_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen11_3.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen11_3.C [inlineEverything_specimen11_3.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen11_3.C"									 		NINLINE="$(echo specimen11_3.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen11_3.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen12_3.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen12_3.C [inlineEverything_specimen12_3.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen12_3.C"									 		NINLINE="$(echo specimen12_3.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen12_3.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen13_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen13_1.C [inlineEverything_specimen13_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen13_1.C"									 		NINLINE="$(echo specimen13_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen13_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen14_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen14_1.C [inlineEverything_specimen14_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen14_1.C"									 		NINLINE="$(echo specimen14_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen14_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen15_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen15_1.C [inlineEverything_specimen15_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen15_1.C"									 		NINLINE="$(echo specimen15_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen15_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen16_4.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen16_4.C [inlineEverything_specimen16_4.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen16_4.C"									 		NINLINE="$(echo specimen16_4.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen16_4.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen17_10.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen17_10.C [inlineEverything_specimen17_10.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen17_10.C"									 		NINLINE="$(echo specimen17_10.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen17_10.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen18_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen18_1.C [inlineEverything_specimen18_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen18_1.C"									 		NINLINE="$(echo specimen18_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen18_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen19_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen19_1.C [inlineEverything_specimen19_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen19_1.C"									 		NINLINE="$(echo specimen19_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen19_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen20_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen20_1.C [inlineEverything_specimen20_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen20_1.C"									 		NINLINE="$(echo specimen20_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen20_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen21_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen21_1.C [inlineEverything_specimen21_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen21_1.C"									 		NINLINE="$(echo specimen21_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen21_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/specimen22_1.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen22_1.C [inlineEverything_specimen22_1.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/specimen22_1.C"									 		NINLINE="$(echo specimen22_1.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything.conf inlineEverything_specimen22_1.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_01.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_01.C [inlineEverything_testWithTokenStreamUnparsing_01.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_01.C"									 		NINLINE="$(echo testWithTokenStreamUnparsing_01.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything -rose:unparse_tokens"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything_withTokenStreamUnparsing.conf inlineEverything_testWithTokenStreamUnparsing_01.C.passed)

add_test(
  NAME "inlineEverything___CMAKE_SOURCE_DIR_/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_02.C"
  COMMAND ${CMAKE_SOURCE_DIR}/scripts/rth_run.pl  srcdir=${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests top_srcdir=${CMAKE_SOURCE_DIR} blddir=$(pwd) top_blddir=${CMAKE_BINARY_DIR} VALGRIND=												 		TITLE="inlineEverything ${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_02.C [inlineEverything_testWithTokenStreamUnparsing_02.C.passed]"								 		SPECIMEN="${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/testWithTokenStreamUnparsing_02.C"									 		NINLINE="$(echo testWithTokenStreamUnparsing_02.C |sed --regexp-extended 's/specimen[0-9]+_([0-9]+).*/\1/')"	 		TRANSLATOR="$(pwd)/inlineEverything -rose:unparse_tokens"								 		${CMAKE_SOURCE_DIR}/tests/nonsmoke/functional/roseTests/astInliningTests/inlineEverything_withTokenStreamUnparsing.conf inlineEverything_testWithTokenStreamUnparsing_02.C.passed)

